# MediaWiki with MariaDB
version: '3'
services:
  database:
    image: xlp0/mariadb
    restart: always
    networks:
      - common
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      # The following line is replaced by a script in
      # provision/mariadb/01-databases.sql because we need to initialize 2
      # databases: my_wiki and eauth.
      # MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./mountPoint/mariadb:/var/lib/mysql
      - ./provision/mariadb:/docker-entrypoint-initdb.d
      - ./mountPoint/backup:/backup
      - ./mountPoint/MediaWiki_Backup:/MediaWiki_Backup
  mediawiki:
    image: fantasticofox/pkc:latest
    restart: always
    networks:
      - common
      # Do not delete the comment below! It is used for adding an external
      # network for deploying an internet-accessible PKC .
      #WEBPUBLICPLACEHOLDER
    ports:
      - ${PORT_NUMBER}:80
    entrypoint: '/var/www/html/aqua/entrypoint_mediawiki.sh'
    environment:
      - VIRTUAL_HOST=${MEDIAWIKI_HOST}
      - LETSENCRYPT_HOST=${MEDIAWIKI_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      # Unfortunately, Eauth uses a generically named "PORT"
      # for their PORT variable.
      - PORT=${PORT}
    volumes:
      - ./mountPoint/images:/var/www/html/images
      - ./mountPoint/extensions/DataAccounting:/var/www/html/extensions/DataAccounting
      - ./mountPoint/backup:/backup
      - ./aqua:/var/www/html/aqua
      - ./mountPoint/MediaWiki_Backup:/MediaWiki_Backup
    depends_on:
      - database
      - eauth
  eauth:
    image: pelith/node-eauth-server:latest
    restart: always
    networks:
      - common
      # Do not delete the comment below! It is used for adding an external
      # network for deploying an internet-accessible PKC .
      #WEBPUBLICPLACEHOLDER
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    environment:
      - VIRTUAL_HOST=${EAUTH_HOST}
      - LETSENCRYPT_HOST=${EAUTH_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=${PORT}
    volumes:
      - ./aqua/eauth_seed.js:/usr/src/app/components/seeders/20190725062038-oauth_clients.js
      # TODO this will become obsolete after pelith fixes their installation bug
      - ./aqua/eauth_config.json:/usr/src/app/config/config.json
    depends_on:
      - database
networks:
  # We specify the internal network as common, so that the services in this
  # docker-compose.yml can be configured to interact with the services in the
  # other, separate docker-compose.yml using external networks.
  common:
