# This Docker Compose file is used to run the project in Docker for development.
# Opens database for local connections on port 3306 with root access.
#
# Usage:
#   ln -s docker-compose.dev.yml docker-compose.override.yml
#   docker compose up [-d]
#
# To go back to running the published image:
#   rm docker-compose.override.yml
#
# DefaultSettings for MediaWiki
# @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
#
# Settings and defaults for mysqldump
# @see https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html
#
# Note issue with Volumes affecting Docker Desktop (for Mac) and also affecting Windows (WSL2):
# https://github.com/docker/for-mac/issues/4822 https://github.com/docker/for-win/issues/12323
#
# Workaround VM limitation with a Busybox container to access the data inside the volume:
#   docker run --rm --volumes-from micro-pkc-mediawikibackup-dev busybox ls
#
version: '3'
services:
  database:
    container_name: micro-pkc-database-dev
    image: mariadb:${MARIADB_VERSION:-latest}
    ports:
      - "3306:3306"
    restart: unless-stopped
  
  mediawikibackup:
    container_name: micro-pkc-mediawikibackup-dev
    environment:
      USERNAME: wikiuser
      PASSWORD: "example"
      CRON_SCHEDULE: "0 */2 * * *" # At minute 0 past every 2nd hour.
      EXTRA_OPTS: "--single-transaction --skip-dump-date --verbose"
