# This Docker Compose file is used to run the project's published image
#
# Usage: docker compose up [-d] [--env-file=path/to/file]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3'
volumes:
  mysql-data: {}
  mysql-backups-data: {}
services:
  database:
    container_name: micro-pkc-database
    image: mariadb:10.6.4
    restart: always
    networks:
      - common
    environment:
      # The following line is replaced by a script in
      # provision/mariadb/01-databases.sql because we need to initialize 2
      # databases: my_wiki and eauth.
      # MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - "./provision/mariadb:/docker-entrypoint-initdb.d"
      - "mysql-data:/var/lib/mysql"
      - "mysql-backups-data:/backup"
      - ./mountPoint/MediaWiki_Backup:/MediaWiki_Backup
  databasebackup:
    container_name: micro-pkc-databasebackup
    image: selim13/automysqlbackup:2.6-9
    restart: unless-stopped # healthcheck on port 18080
    networks:
      - common
    volumes:
      - "mysql-backups-data:/backup"
    environment:
      USERNAME: wikiuser
      PASSWORD: "example"
      DBHOST: database
      DBEXCLUDE: "performance_schema information_schema"
      CRON_SCHEDULE: "0 22 * * 1-7" # At 22:00 on every day-of-week from Monday through Sunday.
      LATEST: "yes"
      SEPDIR: "no"
      EXTRA_OPTS: "--single-transaction --log-error=/var/log/mysqld.log"
    depends_on:
      - database
  mediawiki:
    container_name: micro-pkc-mediawiki
    image: 0xc000007b/micro-pkc-mediawiki:37-1php74
    restart: always
    networks:
      - common
      # Do not delete the comment below! It is used for adding an external
      # network for deploying an internet-accessible PKC .
      #WEBPUBLICPLACEHOLDER
    ports:
      - ${MEDIAWIKI_PORT}:80
    entrypoint: '/var/www/html/aqua/entrypoint_mediawiki.sh'
    environment:
      - VIRTUAL_HOST=${MEDIAWIKI_HOST}
      - LETSENCRYPT_HOST=${MEDIAWIKI_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - EAUTH_PORT=${EAUTH_PORT}
    volumes:
      - ./mountPoint/images:/var/www/html/images
      - ./mountPoint/extensions/DataAccounting:/var/www/html/extensions/DataAccounting
      - ./mountPoint/backup:/backup
      - ./aqua:/var/www/html/aqua
      - ./mountPoint/MediaWiki_Backup:/MediaWiki_Backup
    depends_on:
      - database
      - eauth
  eauth:
    container_name: micro-pkc-eauth
    image: 0xc000007b/micro-pkc-eauth
    restart: always
    networks:
      - common
      # Do not delete the comment below! It is used for adding an external
      # network for deploying an internet-accessible PKC .
      #WEBPUBLICPLACEHOLDER
    env_file:
      - .env
    ports:
      - ${EAUTH_PORT}:${EAUTH_PORT}
    environment:
      - VIRTUAL_HOST=${EAUTH_HOST}
      - LETSENCRYPT_HOST=${EAUTH_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=${EAUTH_PORT}
    depends_on:
      - database

networks:
  # We specify the internal network as common, so that the services in this
  # docker-compose.yml can be configured to interact with the services in the
  # other, separate docker-compose.yml using external networks.
  common: {}

