name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: codespell-project/actions-codespell@master
